mysite/food/urls.py
from django.urls import path

from . import views

app_name = 'food'

urlpatterns = [
    path('', views.index, name='index'),
    path('item', views.item, name='item'),
    path('item/<item_id>', views.detail, name='detail'),
    path('add', views.create_item, name="create_item"),
    path('update/<id>/', views.update_item, name='update_item'),
    path('delete/<id>/', views.delete_item, name='delete_item')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('food.urls')),
    path('register', user_views.register, name='register'),
]

mysite/food/models.py
from django.db import models

# Create your models here.

class Item(models.Model):
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=500)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500, default='https://picsum.photos/640/360')

    def __str__(self):
        return self.item_name

mysite/users/models.py
from django.db import models

# Create your models here.

mysite/food/forms.py
from django import forms

from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name', 'item_desc', 'item_price', 'item_image']

mysite/food/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.template import loader

from .models import *
from .forms import ItemForm

# Create your views here.
def index(request):
    item_list = Item.objects.all()
    template = loader.get_template('index.html')
    context = {
        'item_list': item_list,
    }
    return HttpResponse(template.render(context, request))

def item(request):
    return HttpResponse('This is items menu.')

def detail(request, item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        'item':item,
    }
    return render(request, 'detail.html', context)

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request, 'item_form.html', {'form': form})

def update_item(request, id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request, 'item_form.html', {'form':form, 'item':item})


def delete_item(request, id):
    item = Item.objects.get(id=id)
    # if request.method == 'POST':
    item.delete()
    return redirect('food:index')
    
    # return render(request, 'item_delete.html', {'item' : item})

mysite/users/views.py
from django.shortcuts import render, redirect

from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages

# Create your views here.

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Welcome {username}, Your account created successfully')
            return redirect('food:index')
    else:
        form = UserCreationForm()
    return render(request, 'users/register.html', {'form':form})

mysite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}" </head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script> -->

<body>

    <nav class="navbar navbar-dark bg-dark">
        <a href="#" class="navbar-brand">FoodApp</a>

        <div class="navbar">
            <ul class="nav justify-content-end">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'food:create_item' %}">Add Item</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Delete Item</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">View Item</a>
                </li>
            </ul>
        </div>
    </nav>


    {% block content %}

    {% endblock content %}

</body>

</html>

mysite/templates/detail.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img class="card img-fluid" src="{{item.item_image}}">
        </div>
        <div class="col-md-6">
            <h1><b> {{item.item_name}} </b></h1>
            <h1> {{item.item_desc}} </h1>
            <h1> RS. {{item.item_price}} </h1>
            <a href="{% url 'food:delete_item' item.id %}" class="btn btn-danger">Delete</a>
        </div>
    </div>
</div>

{% endblock content %}

mysite/templates/index.html
{% extends 'base.html' %}

{% block content %}
{% for item in item_list %}


<div class="row">
    <div class="col-md-3 offset-md-2">
        <img class="card img-fluid" src="{{ item.item_image }}" />
    </div>
    <div class="col-md-4">
        <h3>{{ item.item_name }}</h3>
        <h5>{{ item.item_desc }}</h5>
        <h4>{{ item.item_price }}</h4>
    </div>
    <dvi class="col-md-2">
        <a href=" {% url 'food:update_item' item.id %} " class="btn btn-success">Edit</a>
        <a href=" {% url 'food:detail' item.id %} " class="btn btn-success">Details</a>
    </dvi>
</div>

{% endfor %}

{% endblock content %}

mysite/templates/item_delete.html
<form action="POST">
    {% csrf_token %}

    <h2>Are you sure want to delete {{item.item_name}}</h2>
    <button type="submit">Confirm</button>
</form>

mysite/templates/item_form.html
{% extends 'base.html' %}


{% block content %}

<form method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit">Save</button>
</form>

{% endblock content %}

mysite/templates/users/register.html
<form action="post">
    {% csrf_token %}

    {{ form }}
    <button type="submit">Sign Up</button>
</form>